# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022-2024 Dell Inc, or its subsidiaries.
---
argument_specs:
  main:
    version_added: "1.0.0"
    short_description: Role to manage DPU BMC session
    description:
      - Role to manage (create and delete) the DPU BMC authentication session.
    options:
      hostname:
        type: str
        description:
          - DPU BMC IP Address.
      username:
        type: str
        description:
          - DPU BMC username.
      password:
        type: str
        description:
          - DPU BMC user password.
      auth_token:
        type: str
        description:
          - Security token for authentication with DPU BMC.
      https_port:
        type: int
        description:
          - DPU BMC port.
        default: 443
