# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022-2024 Dell Inc, or its subsidiaries.

---
# vars file for bmc_session

bmc_session_delegate: "{{ lookup('ansible.builtin.env', 'RUNON', default='localhost') }}"
