---
# tasks file for bmc_session

- name: Create session
  community.general.redfish_command:
    category: Sessions
    command: CreateSession
    baseuri: "{{ inventory_hostname }}"
    username: "{{ dpu_bmc_username }}"
    password: "{{ dpu_bmc_password }}"
  delegate_to: localhost
  register: result

- name: Extract session details from login result
  ansible.builtin.set_fact:
    bmc_session_token: "{{ result.session.token }}"
    bmc_session_uri: "{{ result.session.uri }}"

- name: Print Session Tokens
  ansible.builtin.debug:
    msg:
      - "{{ bmc_session_token }}"
      - "{{ bmc_session_uri }}"

- name: Delete session
  community.general.redfish_command:
    category: Sessions
    command: DeleteSession
    baseuri: "{{ inventory_hostname }}"
    auth_token: "{{ bmc_session_token }}"
    session_uri: "{{ bmc_session_uri }}"
  delegate_to: localhost
