# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022-2024 Dell Inc, or its subsidiaries.
---
argument_specs:
  main:
    version_added: "1.0.0"
    short_description: Role to reset and restart DPU BMC
    description:
      - Role to reset and restart DPU BMC.
    options:
      hostname:
        type: str
        description:
          - DPU BMC IP Address.
      username:
        type: str
        description:
          - DPU BMC username.
      password:
        type: str
        description:
          - DPU BMC user password.
      auth_token:
        type: str
        description:
          - Security token for authentication with DPU BMC.
      https_port:
        type: int
        description:
          - DPU BMC port.
        default: 443
      bmc_reboot_should_wait:
        description:
          - Wait for the BMC to restart.
        type: bool
        default: true
      bmc_reboot_wait_timeout:
        description:
          - Seconds to wait for the BMC to restart.
        type: int
        default: 120
