# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022-2024 Dell Inc, or its subsidiaries.

---
# tasks file for get_bmc_facts

- name: Get Firmware Inventory
  community.general.redfish_info:
    category: Update
    command: GetFirmwareInventory
    baseuri: "{{ inventory_hostname }}"
    username: "{{ dpu_bmc_username }}"
    password: "{{ dpu_bmc_password }}"
    # auth_token: "{{ dpu_bmc_token }}"
  register: result
  delegate_to: "{{ get_bmc_facts_delegate }}"

- name: Extract all FW versions to facts
  ansible.builtin.set_fact:
    get_bmc_facts_all_fw_versions: "{{ get_bmc_facts_all_fw_versions | default({}) | combine({item['Id'] | lower: item['Version']}) }}"
  loop: "{{ result.redfish_facts.firmware.entries }}"
