# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022-2024 Dell Inc, or its subsidiaries.

---
# tasks file for get_bmc_facts

- name: Get Firmware Inventory
  community.general.redfish_info:
    category: Update
    command: GetFirmwareInventory
    baseuri: "{{ inventory_hostname }}"
    username: "{{ dpu_bmc_username }}"
    password: "{{ dpu_bmc_password }}"
  register: result
  delegate_to: localhost

- name: Extract all FW versions to facts
  ansible.builtin.set_fact:
    bmc_fw_version: "{{ bmc_fw_version | default({}) | combine({ item['Id'] | lower : item['Version'] }) }}"
  loop: "{{ result.redfish_facts.firmware.entries }}"

#- name: Print facts
#  ansible.builtin.debug:
#    var: vars.bmc_fw_version
#  delegate_to: localhost
