name: Ansible

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    name: Build collection
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        ansible-version: [stable-2.17, stable-2.15, stable-2.16, devel]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install ansible (${{ matrix.ansible-version }})
        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible-version }}.tar.gz --disable-pip-version-check

      - name: Build a collection tarball
        run: ansible-galaxy collection build --output-path "${GITHUB_WORKSPACE}/.cache/collection-tarballs"

      - name: Store migrated collection artifacts
        uses: actions/upload-artifact@v1
        with:
          name: collection
          path: .cache/collection-tarballs

  ###
  # Unit tests (OPTIONAL)
  # 
  # https://docs.ansible.com/ansible/latest/dev_guide/testing_units.html

  unit:
    name: Unit Tests
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         python-version: ["3.10", "3.11"]
         ansible-version: [stable-2.15, stable-2.16, stable-2.17]

    steps:
      - name: Perform unit testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@v1.15.0
        with:
          testing-type: units
          coverage: always
          ansible-core-version: ${{ matrix.ansible-version }}
          target-python-version: ${{ matrix.python-version }}

  ###
  # Sanity tests (REQUIRED)
  #
  # https://docs.ansible.com/ansible/latest/dev_guide/testing_sanity.html

  sanity:
    name: Sanity Tests
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
         python-version: ["3.10", "3.11"]
         ansible-version: [stable-2.15, stable-2.16, stable-2.17]

    steps:
      - name: Perform sanity testing
        uses: ansible-community/ansible-test-gh-action@v1.15.0
        with:
          ansible-core-version: ${{ matrix.ansible-version }}
          target-python-version: ${{ matrix.python-version }}
          testing-type: sanity
          pull-request-change-detection: true
          coverage: never

  lint:
    name: Ansible lint
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
         python-version: ["3.10", "3.11", "3.12"]
         ansible-version: [stable-2.15, stable-2.16, stable-2.17]

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - name: Checkout the source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed for progressive mode to work

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install ansible (${{ matrix.ansible-version }}) version
        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible-version }}.tar.gz --disable-pip-version-check

      - name: Install ansible lint
        run: pip install ansible-lint jmespath --disable-pip-version-check

      - name: Download migrated collection artifacts
        uses: actions/download-artifact@v1
        with:
          name: collection
          path: .cache/collection-tarballs

      - name: Install collection build
        run: ansible-galaxy collection install .cache/collection-tarballs/*.tar.gz 

      - name: Run Ansible lint
        run: ansible-lint --show-relpath
        working-directory: /home/runner/work/ansible-opi-dpu/ansible-opi-dpu
